### ISSUE TITLE
Modal and hover on an hour always show red x

### ISSUE THREAD

**Issue by Lenni009** [NMSCD/HG-Server-Status#2]
When hovering over one bar or opening its modal, there will always be a red cross instead of the status being dynamic based on what actually happened.

How to reproduce:
1. Hover over any green bar
2. See red cross in the tooltip
3. Click on green bar
4. See red cross in the modal title, despite the entries being green

**Comment by Khaoz-Topsy** [comment]
Should be fixed now 😋
